version: "3.9"
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
            PW_SECRET: ${PW_SECRET}
        ports:
            - 5433:5432
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/data:/var/lib/postgresql/data
    app:
        image: node:18-alpine
        environment:
            PG_USER: ${PG_USER}
            PG_PASSWORD: ${PG_PASSWORD}
            PG_DATABASE: ${PG_DATABASE}
            PW_SECRET: ${PW_SECRET}
            JW_SECRET: ${JW_SECRET}
        depends_on:
            - db
