version: "3.9"
services:
    client:
        container_name: blogplatform-client
        build: ./client
        environment:
            PG_USER: ${PG_USER}
            PG_PASSWORD: ${PG_PASSWORD}
            PG_DATABASE: ${PG_DATABASE}
            PW_SECRET: ${PW_SECRET}
            JW_SECRET: ${JW_SECRET}
        ports:
            - 3000:3000
        volumes:
            - ./client:/client
            - /client/node_modules
            - /client/.next
        depends_on:
            - db
    db:
        container_name: blogplatform-db
        image: postgres:latest
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
            PW_SECRET: ${PW_SECRET}
        ports:
            - 5433:5432
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/data:/var/lib/postgresql/data
        expose:
            - 5432
